### ISSUE TITLE
Slow to update to new curseforge releases

### ISSUE THREAD

**Issue by profjb58** [comp500/packwiz#15]
It seems to be quite difficult to grab brand new releases for mods from curse forge, specifically mods that have been updated within about the past 2 days.

Tried with: https://www.curseforge.com/minecraft/mc-mods/gift-it/files, https://www.curseforge.com/minecraft/mc-mods/knowyourknot-enderporter and https://www.curseforge.com/minecraft/mc-mods/bits-and-chisels all of which wouldn't return the latest files

Tried using the ```--addon-id```, ```--file-id``` approach but got the same results

**Comment by comp500** [comment]
Not much I can do about this, they just aren't showing up in the API at all - this is on CurseForge's end.
