### ISSUE TITLE
Command Update does not update Modrinth mods

### ISSUE THREAD

**Issue by FlashyReese** [comp500/packwiz#19]
![image](https://user-images.githubusercontent.com/30311066/110830843-42d9b500-825f-11eb-95ca-2efb57e63d07.png)

**Comment by comp500** [comment]
Could you send the metadata .toml files for those mods, I'm not sure exactly what is going on here.

**Comment by FlashyReese** [comment]
Hydrogen: https://github.com/FlashyReese/Reereum/blob/1.16.x/mods/hydrogen.toml
EBE: https://github.com/FlashyReese/Reereum/blob/1.16.x/mods/ebe.toml

**Comment by comp500** [comment]
I've pushed https://github.com/comp500/packwiz/commit/8f9b08e3a4273a29ce22715de5b937e64df75fc4 which should fix it, could you try that?

**Comment by FlashyReese** [comment]
Looks like it's fixed.

**Comment by comp500** [comment]
Thanks for reporting the bug!
