### ISSUE TITLE
Add option to install curseforge mod by curseforge link

### ISSUE THREAD

**Issue by ZangeloRaj** [comp500/packwiz#2]
Some mods are cursed with the flaws of CF's mod search and don't show up in the first 10 results, no matter how you word your search. I think it would be a good idea if you can have a CF link to the mod's page like `packwiz curseforge install https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes`.

**Comment by comp500** [comment]
It should already work exactly as you have suggested :)

**Comment by ZangeloRaj** [comment]
It keeps on saying `mod not available for this Minecraft version`

**Comment by comp500** [comment]
What game version is in your pack.toml? It might be the curseforge API being bad, you may want to copy the file URL like [https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes/files/2937872](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes/files/2937872) (as it works with that too)

**Comment by ZangeloRaj** [comment]
That did the trick. Thanks a lot!
