### ISSUE TITLE
Segmentation violation when using curseforge detect

### ISSUE THREAD

**Issue by IITFA** [comp500/packwiz#20]
`$ ../packwiz/packwiz curseforge detect
Loading modpack...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8908bb]

goroutine 1 [running]:
github.com/comp500/packwiz/curseforge.glob..func1.1(0x9815bc, 0x4, 0x0, 0x0, 0xa26c00, 0xc0001690e0, 0x6, 0x6)
	/home/username/tmp/packwiz/curseforge/detect.go:38 +0x3b
path/filepath.Walk(0x9815bc, 0x4, 0xc0001ef818, 0x2, 0xc00017f408)
	/usr/local/go/src/path/filepath/path.go:499 +0x7e
github.com/comp500/packwiz/curseforge.glob..func1(0xcc6c40, 0xcfffa0, 0x0, 0x0)
	/home/username/tmp/packwiz/curseforge/detect.go:37 +0x3be
github.com/spf13/cobra.(*Command).execute(0xcc6c40, 0xcfffa0, 0x0, 0x0, 0xcc6c40, 0xcfffa0)
	/home/username/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xcc6240, 0xc000000180, 0x200000003, 0xc000000180)
	/home/username/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
	/home/username/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/comp500/packwiz/cmd.Execute()
	/home/username/tmp/packwiz/cmd/root.go:24 +0x31
main.main()
	/home/username/tmp/packwiz/main.go:12 +0x25`

Totally new to packwiz.
go version go1.16.3 linux/amd64
MX Linux

**Comment by comp500** [comment]
It seems like there was another error during traversal of your mod directory, but my code wasn't passing the error up correctly, so it segfaulted. I've pushed a fix for the segfault, hopefully the error is more descriptive now.

**Comment by IITFA** [comment]
Now I get this error:
../packwiz/packwiz curseforge detect
Loading modpack...
lstat mods: no such file or directory

**Comment by comp500** [comment]
The detect command assumes you have a mods folder from which to read mods from. What did you want to use it for?

**Comment by IITFA** [comment]
To keep my rather large modpack updated.

**Comment by comp500** [comment]
What I mean is: the detect command reads .jar files in the mods directory, and tries to find them on CurseForge, to turn them into .toml files you can manage/update/distribute using packwiz. If you already have .toml files (e.g. using `packwiz cf install`) this isn't necessary. If you don't have any mods, you should use the `packwiz cf install` commands to get the metadata.

If you do actually want to turn an existing folder of .jar files into .toml files for managing with packwiz, you'll need to put them in a folder called mods, which doesn't seem to exist currently.

**Comment by IITFA** [comment]
The mods being tested are in a directory named mods already. The below attachment shows from clean. The curseforge detect still shows the latest error I posted.

![test](https://user-images.githubusercontent.com/28982837/114456401-56649c80-9bcc-11eb-96b2-2a1e67960e8c.png)

**Comment by comp500** [comment]
Ah, I see - you need to be in a folder above the mods folder, the idea being that the folder containing pack.toml and index.toml is the entire modpack, so you can also add config files, quests, resource packs, etc.

**Comment by IITFA** [comment]
lol

![tmp3](https://user-images.githubusercontent.com/28982837/114461353-5b781a80-9bd1-11eb-83c7-5cc2cb32a4a3.png)

**Comment by comp500** [comment]
The pack.toml and index.toml files need to be in `~/tmp/` as well 😛

**Comment by IITFA** [comment]
There we go lol. Well, at least this issue thread might shed some light on possible documentation that should be covered lol.
