### ISSUE TITLE
Per-file mod loader filtering on CurseForge

### ISSUE THREAD

**Issue by kb-1000** [comp500/packwiz#26]
The same happens to Music Disks Galore.
Steps to reproduce:
1. create a Fabric pack containing Xaeros' Minimap (does not matter if outdated or not)
2. use `packwiz update --all`
3. see that Xaeros' Minimap has been replaced with the Forge version

**Comment by comp500** [comment]
This is planned, but it'll likely be opt-in for CurseForge as implementing it properly will slow down update checks a lot

**Comment by comp500** [comment]
Recent changes to CurseForge's API have made this much easier; I'll look at implementing this soon.

**Comment by comp500** [comment]
Fixed by https://github.com/comp500/packwiz/commit/896b9548de7a7d905e7ae0693b44c65b2de85395
