### ISSUE TITLE
Root folder config option for refreshes

### ISSUE THREAD

**Issue by haykam821** [comp500/packwiz#27]
Even though `index.toml` is in a subdirectory, files from the working directory where `pack.toml` is found are added.

**Comment by comp500** [comment]
The code does currently consider the `pack.toml` folder to be the pack root:
https://github.com/comp500/packwiz/blob/49d7b26b2e67ae843688d4a0bb7525d1826c3571/core/index.go#L176-L177

I think I'll just add a pack root config option to `pack.toml`, as making the index file the root isn't really intuitive.

**Comment by comp500** [comment]
Future context: `pack-root` was removed; `index.toml` is now treated as the root (see https://github.com/packwiz/packwiz/issues/39)
