### ISSUE TITLE
When the pack-root option is set in pack.toml, export should treat it as overrides instead of a subdirectory of overrides

### ISSUE THREAD

**Issue by GreatestFool** [comp500/packwiz#39]
Currently, if you have `pack-root` set in pack.toml, e.g. packdata in this case, and then run something like `packwiz curseforge export`, packdata is added as a subdirectory of `overrides` instead of having the contents of the directory `packdata` be directly in `overrides`.

Here's an example of what the `pack-root` directory structure looks like, in case I'm being unclear:

```
packdata (pack-root)
└─ test.txt
```

Current behavior makes the zip file generated when using `packwiz curseforge export` contain:

```
<modpack-name>-<version>.zip
└─ overrides
|  └─ packdata
|     └─ test.txt
└─ manifest.json
└─ modlist.html
```

Preferable output would be:

```
<modpack-name>-<version>.zip
└─ overrides
|  └─ test.txt
└─ manifest.json
└─ modlist.html
```

This will let you dump most of the actual modpack related stuff in the `pack-root` specified directory, and have it properly included during export and help organize things a little :)

(optional, but related): A way to have index.toml in the `pack-root` specified directory without getting `open index.toml: The system cannot find the file specified.` when trying to run packwiz commands. E.g. by having an `[option]` that specifies the location of it, cuz then you could add that to the `pack-root` directory too.

**Comment by GreatestFool** [comment]
Hmm, this is also relevant to when running `packwiz serve --basic`, the same issue persists here. In MultiMC, it installs the mods, but to a subdirectory of `.minecraft` equal to the value of `pack-root` as explained in the OP, while the actual mods folder is left empty.

![image](https://user-images.githubusercontent.com/3003484/120885406-fcd78780-c5e8-11eb-9d64-4ab063933365.png)
![image](https://user-images.githubusercontent.com/3003484/120885412-082ab300-c5e9-11eb-8e63-698704cc4214.png)

**Comment by comp500** [comment]
Ah... that's a major oversight. I guess I might have to add direct support for it in packwiz-installer, or leave it for the new pack format. Just making the `index.toml` file the root for now (without the pack-root option) would be a reasonable solution. 

> (optional, but related): A way to have index.toml in the `pack-root` specified directory without getting `open index.toml: The system cannot find the file specified.` when trying to run packwiz commands. E.g. by having an `[option]` that specifies the location of it, cuz then you could add that to the `pack-root` directory too.

I think this should already be possible? In `pack.toml` the location of the `index.toml` file should be specified:
```toml
[index]
file = "index.toml" # <- change this to the path you want to use
hash-format = "sha256"
hash = "ec33032d129af107ac243a9afd816d1cf297693794be1249424a98290d7cafc0"
```

**Comment by GreatestFool** [comment]
> Ah... that's a major oversight. I guess I might have to add direct support for it in packwiz-installer, or leave it for the new pack format. Just making the index.toml file the root for now (without the pack-root option) would be a reasonable solution.

Well, with how it is works now, I assume you'd have to add it to the packwiz-installer as well as packwiz. Considering packwiz needs to be able to export it for both curseforge in a way that it'd be added properly once imported in something like MultiMC, GDLauncher or similar. Likewise, the packwiz-installer, would probably also need code to define how to unpack/install a pack if pack-root is set.

Though, I have no familiarity with Go or how the program is structured internally, so I assume you'll have a better idea on the better solution here :)

Regardless, I personally only need a supported curseforge format, considering I have no site to host from, so despite this being an issue, I'll _probably_ be able to cook up some kind of Python abomination to fix the zipped folder structure afterwards as a temporary solution.

> I think this should already be possible? In `pack.toml` the location of the `index.toml` file should be specified:
> 
> ```toml
> [index]
> file = "index.toml" # <- change this to the path you want to use
> hash-format = "sha256"
> hash = "ec33032d129af107ac243a9afd816d1cf297693794be1249424a98290d7cafc0"
> ```

Welp, I completely missed that. Tested it and it works, thanks for the help :)
