### ISSUE TITLE
cant download fabric version of a mod.

### ISSUE THREAD

**Issue by TypicalShavonne** [comp500/packwiz#4]
its dont allow to choose the file that is fabricmod, i need fabric not forge version

**Comment by comp500** [comment]
Currently there's no file filtering, so you'll need to specify the file manually. The easiest way to do this is to pass the URL of the file to `packwiz install`, for example `packwiz install https://www.curseforge.com/minecraft/mc-mods/worldedit/files/3039223`.

If that also fails, you can try specifying the addon/project ID as well (it's specified on the curseforge page), for example `packwiz install --addon-id 225608 --file-id 3039223`

**Comment by TypicalShavonne** [comment]
Oh, thanks :D

**Comment by TypicalShavonne** [comment]
> Currently there's no file filtering, so you'll need to specify the file manually. The easiest way to do this is to pass the URL of the file to `packwiz install`, for example `packwiz install https://www.curseforge.com/minecraft/mc-mods/worldedit/files/3039223`.
> 
> If that also fails, you can try specifying the addon/project ID as well (it's specified on the curseforge page), for example `packwiz install --addon-id 225608 --file-id 3039223`

cant believe that you still answer Issue when u dont update this project after months :D

**Comment by TypicalShavonne** [comment]
it said `Error: unknown command "install" for "packwiz"
Run 'packwiz --help' for usage.
unknown command "install" for "packwiz"`

**Comment by comp500** [comment]
Whoops, I meant `packwiz cf install` 😄
And yeah, I'm still planning to rewrite this thing, just haven't had much motivation recently.

**Comment by TypicalShavonne** [comment]
> Whoops, I meant `packwiz cf install` 😄
> And yeah, I'm still planning to rewrite this thing, just haven't had much motivation recently.

haha, thanks :D it is so useful for fabric mods because it dont have a mod manager that work efficient like forge
