### ISSUE TITLE
Curseforge mod search is broken in recent versions.

### ISSUE THREAD

**Issue by baltassarmonkey** [comp500/packwiz#44]
In the latest [version](https://github.com/comp500/packwiz/actions/runs/958873260), searching for mods will just result in the 10 most popular mods of all time being displayed regardless of the search terms.

Example:

`$ packwiz cf install automatic`
`Searching CurseForge...`
`0) Cancel`
`1) *Just Enough Items (JEI)`
`2) Mouse Tweaks`
`3) AutoRegLib`
`4) JourneyMap`
`5) AppleSkin`
`6) Baubles`
`7) Biomes O' Plenty`
`8) Iron Chests`
`9) Bookshelf`
`10) Storage Drawers`

I even tried giving the url to the curseforge page, but that also produced the same result.
Rolled back to a [version](https://github.com/comp500/packwiz/actions/runs/933651074) from a few days ago, and the issue is no longer there.

**Comment by comp500** [comment]
Could you send your `pack.toml`?
