### ISSUE TITLE
A flag to keep external mods on update

### ISSUE THREAD

**Issue by Madis0** [comp500/packwiz#45]
When updating the modpack via packwiz with a flag set (e.g. `-keep-existing`), the updater should only add new mods or update existing ones' versions, but not remove any mods that are not listed in the manifest.

(Initially suggested by an user of my modpack: https://github.com/Madis0/fabulously-optimized/issues/81)

**Comment by Remty5** [comment]
Well, packwiz doesn't seem to care about the mods I added. The script I made only removes mods based on the ones I don't need.

**Comment by Madis0** [comment]
Oh, then I misunderstood you. I guess packwiz could do that as well (e.g. an user-defined ignore list) but that'd be used much less so it is probably not worth adding to packwiz.

**Comment by comp500** [comment]
I am planning similar functionality - see https://github.com/comp500/packwiz-installer/issues/6
