### ISSUE TITLE
Modrinth updating does not check primary field, which can cause dev/sources jars to be added

### ISSUE THREAD

**Issue by wafflecoffee** [comp500/packwiz#50]
As in the title. First discovered thanks to [rainbowify](https://api.modrinth.com/api/v1/mod/rainbowify); I had [1.1.0](https://api.modrinth.com/api/v1/version/vwhDgf4A) but updating to [1.1.2](https://api.modrinth.com/api/v1/version/aPfyFNin) caused the dev jar to be the candidate, despite the non-dev jar being set as the primary.
`rainbowify: rainbowify-1.1.0.jar -> rainbowify-1.1.2-dev.jar`

**Comment by comp500** [comment]
I think this is only in the update message, it should still pick the primary file when applying the update. Fixing the message is simple enough though, so I'll do that now.
