### ISSUE TITLE
Send-once / half-ignore specification for configs

### ISSUE THREAD

**Issue by HerrahStrings** [comp500/packwiz#75]
We've got `.packwizignore`, It'd be great if we could have a similar file that specifies that certain files or directories should only be sent one time (e.g. options.txt and servers.dat) and always ignored if they exist. It's clear this functionality is somewhat present, but I'm not sure it always applies when the pack updates / these files change on the server.

**Comment by comp500** [comment]
This is already supported! See `preserve` in https://packwiz.infra.link/reference/pack-format/index-toml/#properties_1. I do want to rename it to be a bit clearer, and probably make it part of normal metadata files.
